<?php

namespace Events;

class TicketEvent{
    const EVENT_TICKET_SUBMITTED = "EVENT_TICKET_SUBMITTED";
    const EVENT_TICKET_PAID = "EVENT_TICKET_PAID";
    const EVENT_TICKET_CONFIRMED = "EVENT_TICKET_CONFIRMED";
    const EVENT_TICKET_PAYMENT_FAILED = "EVENT_TICKET_PAYMENT_FAILED";
    const EVENT_TICKET_COMMISSION_PAID = "EVENT_TICKET_COMMISSION_PAID";
}

?>